apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: devops-nginx
  template:
    metadata:
      labels:
        app: devops-nginx
    spec:
      containers:
        - name: nginx
          image: devops-nginx:1.0
          ports:
            - containerPort: 80
